# Generated by Django 4.0.3 on 2022-04-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('sci-fi', 'sci-fi'), ('adventure', 'adventure'), ('comedy', 'comedy'), ('romance', 'romance'), ('drama', 'drama'), ('documentary', 'documentary')], max_length=15)),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
    ]
