# Generated by Django 4.0.3 on 2022-04-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_movie_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Props',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('use', models.CharField(max_length=260)),
            ],
        ),
    ]
