# Generated by Django 4.0.3 on 2022-04-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_movie_props'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movieprops',
            field=models.ManyToManyField(to='main_app.movie_props'),
        ),
    ]
